### ISSUE TITLE
Feature: Being able to customize the colors and icons

### ISSUE THREAD

**Issue by unatried** [pythops/bluetui#29]
It would be cool if you could customize the UI of bluetui. The syntax (in $HOME/.config/bluetui/config.toml ) could be:
```toml
[colors]
connected="hex, rgb, hsl, cmyk, ncol or hwb"
disconnected=""
connected_trusted=""
trusted=""

[icons]
scanning=""
battery=""
headphones=""
speaker=""
```

**Comment by unatried** [comment]
You could also maybe add an layout option, to change the layout. The person who made #26, wanted this so that would be cool.
Syntax
```toml
layout=[
    "paired",
    "scanning",
    "adpaters"
]

**Comment by unatried** [comment]
A full config would be this
```toml
[navigation]
up = [ "k", "up" ]
down = [ "j", "down" ]
toggle_scanning = "s"
toggle_pairing = "p"
toggle_power = "o"
toggle_discovery = "d"
select = [  " ", "enter" ] # For Connecting and Pairing if in the scanning tab
toggle_trust = "t"
toggle_favorite = "f"
switch_tab = "tab"
unpair = "u"
pair = "p"
rename = "e"

[colors]
connected= " hex, rgb, hsl"
disconnected = ""
connected_trusted = ""
trusted = ""

[icons]
scanning = ""
battery = ""
headphones = ""
speaker = ""
navigation = ""
up = ""
down = ""
space = ""
enter = ""

layout=[
    "paired",
    "scanning",
    "adpaters"
]
```
