### ISSUE TITLE
remapping `toggle_connect` to `c` doesn't work

### ISSUE THREAD

**Issue by Axlefublr** [pythops/bluetui#49]
https://github.com/user-attachments/assets/1868756a-73b4-467b-b687-380765b2c3a0

**Comment by Axlefublr** [comment]
and you know what's the most fascinating thing? I tried remapping to `a` and that worked as expected \
so it seems to be special to `c` \
which is interesting, because I don't think it's a mapping anywhere?

**Comment by Axlefublr** [comment]
my config, for your convenience:
```toml
toggle_scanning = "s"

[paired_device]
unpair = "e"
toggle_connect = "c"
toggle_trust = "t"
rename = "r"

[adapter]
toggle_pairing = "i"
toggle_power = "o"
toggle_discovery = "d"

[new_device]
pair = "a"
```
